//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaUserControl.Common.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder",
        "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance",
            "CA1811:AvoidUncalledPrivateCode")]
        internal Errors()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(
            global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp =
                        new global::System.Resources.ResourceManager("SpaUserControl.Common.Resources.Errors",
                            typeof (Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(
            global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        /// <summary>
        ///   Looks up a localized string similar to E-mail is invalid..
        /// </summary>
        public static string InvalidEmail
        {
            get { return ResourceManager.GetString("InvalidEmail", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid Password!.
        /// </summary>
        public static string InvalidPassword
        {
            get { return ResourceManager.GetString("InvalidPassword", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password confirmation is invalid!.
        /// </summary>
        public static string InvalidPasswordConfirmation
        {
            get { return ResourceManager.GetString("InvalidPasswordConfirmation", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Username is invalid..
        /// </summary>
        public static string InvalidUsername
        {
            get { return ResourceManager.GetString("InvalidUsername", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password not match!.
        /// </summary>
        public static string PasswordNotMatch
        {
            get { return ResourceManager.GetString("PasswordNotMatch", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirme senha:.
        /// </summary>
        public static string Program_Main_Confirme_senha_
        {
            get { return ResourceManager.GetString("Program_Main_Confirme_senha_", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to e-mail.
        /// </summary>
        public static string Program_Main_e_mail_
        {
            get { return ResourceManager.GetString("Program_Main_e_mail_", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Program_Main_Nome
        {
            get { return ResourceManager.GetString("Program_Main_Nome", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string Program_Main_Nova_senha_
        {
            get { return ResourceManager.GetString("Program_Main_Nova_senha_", resourceCulture); }
        }

        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string Program_Main_Usuário_não_encontrado
        {
            get { return ResourceManager.GetString("Program_Main_Usuário_não_encontrado", resourceCulture); }
        }

        public static string InvalidCredentials
        {
            get { return ResourceManager.GetString("Login inválido.", resourceCulture); } 
        }

        public static string UserNotFound
        {
            get { return ResourceManager.GetString("Usuário não encontrado.", resourceCulture); } 
        }

        public static string DuplicateEmail
        {
            get { return ResourceManager.GetString("InvalidEmail-mail já´cadastrado..", resourceCulture); }
        }
    }
}